import React from "react";
import { useNavigate } from "react-router-dom";
const PreviewPlanPage: React.FC = () => {
  const navigate = useNavigate();

  return (
    <div>
      <h1>Preview Plan Page</h1>
      <p>Here you can preview your plans generated by AI.</p>
      <button onClick={() => navigate("/main")}>Go to Main Page</button>
    </div>
  );
};

export default PreviewPlanPage;