import React from "react";

const PreviewPlanPage: React.FC = () => {
  return (
    <div>
      <h1>Preview Plan Page</h1>
      <p>Here you can preview your plans generated by AI.</p>
    </div>
  );
};

export default PreviewPlanPage;
